import { useState, useCallback, useEffect, useRef } from "react";
import DoomHUD from "./DoomHUD";
import PortraitDebugPanel from "./PortraitDebugPanel";
import VisualNovelEngine from "./VisualNovelEngine";
import PushYourLuckEngine from "./PushYourLuckEngine";
import SilkRoad from "./SilkRoad";
import Crusades from "./Crusades";
import GeneratedCampaign from "./GeneratedCampaign";
import GeneratorUI from "./GeneratorUI";
import type { CampaignData } from "../generator/schema";
import josephReconstruction from "../fixtures/joseph-reconstruction.json";
// PRODUCT 2 (narrative) demo — generated by `npm run generate:narrative`.
import narrativeDemo from "../generator/narrative-output.json";
// BRANCHING-STORY engine (new model) — dev/teacher playthrough of real generated stories.
import BranchingPlayer from "./BranchingPlayer";
import type { BranchingStory } from "../generator/branchingStory";
import branching1812 from "../generator/branching-narrative-1812.json";
import branchingReconstruction from "../generator/branching-narrative-reconstruction.json";
import branchingSuffrage from "../generator/branching-narrative-suffrage.json";

const BRANCHING_STORIES: Record<string, BranchingStory> = {
  "branch-1812": branching1812 as BranchingStory,
  "branch-reconstruction": branchingReconstruction as BranchingStory,
  "branch-suffrage": branchingSuffrage as BranchingStory,
};
import ChisholmTriviaEngine, { pickTriviaQuestion, type TriviaQuestion } from "./campaigns/chisholm/trivia";
import type { Objective, RouteState, EventGateQuestion } from "./gameModels";
import { generateObjective, tickObjectives, findNode } from "./gameLogic";
import { CHISHOLM_ROUTE } from "./campaigns/chisholm/routes";
import { CHISHOLM_EVENT_TRIVIA } from "./campaigns/chisholm/eventTrivia";
import {
  useFloatingNumbers, FloatingNumbers,
  useScreenShake, useStatPulse, useResourceTracker,
  StatBox, ResourceBar, StreakFlash,
} from "./GameJuice";
import TrailMap from "./TrailMap";
import { TRAIL_PATH, STOPS, MAP_IMAGE, TOTAL_DISTANCE, getRegionFlavor, isNearSupplyTown } from "./campaigns/chisholm/trailMap";
import { EVENTS } from "./campaigns/chisholm/events";
import { FACES, gf } from "./campaigns/chisholm/pixelFaces";
import { OUTFIT_BUDGET, BASE_CREW, BASE_HORSES, BASE_SUPPLIES, COST_COWBOY, COST_HORSE, COST_SUPPLY, COST_GUN, COST_SPAREPARTS, COST_MEDICAL_GEAR, COST_HORSE_QUALITY, WAGE_COST, WAGE_MORALE, HERD_OPTIONS } from "./campaigns/chisholm/outfitConfig";
import { TOTAL_DAYS, DAYS_PER_TURN, INIT_R, PACES, RESOURCE_LABELS, clampR, getPhrase, getTrailGrade, buildTrailFeedEntries, getPartyMembers } from "./campaigns/chisholm/config";
import { SAGES } from "./campaigns/chisholm/sages";
import type { SageEncounterData } from "./campaigns/types";
import SageEncounter from "./SageEncounter";
import ChisholmParallaxBackground from "./campaigns/chisholm/parallax";
import { ChisholmCampaign } from "./campaigns/chisholm/index";
import { CrusadesCampaign } from "./campaigns/crusades/index";
import FinalExam from "./FinalExam";
import { CampaignLogModal } from "./CampaignLog";
import TradePost, { type TradeOffer } from "./TradePost";
import { CHISHOLM_FINAL_EXAM } from "./campaigns/chisholm/finalExam";

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

interface Resources { [key: string]: number; }
interface Outcome { weight: number; effects: Resources; result: string; earlyEnd?: boolean; }
interface Choice { text: string; effects?: Resources; result?: string; outcomes?: Outcome[]; earlyEnd?: boolean; }
interface PushAttempt { id: string; buttonText: string; successText: string; failureText: string; riskChance: number; rewards: Resources; penalties: Resources; }
interface SageAdvice { name: string; role: string; line: string; }
interface GameEvent { 
  id: string; phase_min: number; phase_max: number; weight: number; title: string; text: string; 
  type?: "standard" | "push_luck"; 
  choices?: Choice[];              
  attempts?: PushAttempt[];        
  leaveText?: string;              
  trivia?: string[];
  sageAdvice?: SageAdvice[];
  riskProfile?: ("LOW" | "MED" | "HIGH")[];
  triviaGate?: boolean;
}
interface Decision { event: string; choice: string; day: number; text?: string; detail?: string; }
interface OutfitConfig {
  herd: number;
  crew: number;
  horses: number;
  supplies: number;
  guns: number;
  spareParts: number;
  medicalGear: number;
  horseQuality: number;
  wages: "low" | "standard" | "good";
  budgetSpent: number;
  startingCash: number;
}

interface GameState {
  day: number; turn: number; resources: Resources;
  phase: "intro" | "outfit" | "sailing" | "event" | "result" | "end" | "trivia" | "event_trivia" | "sage";
  pace: string; distance: number; currentEvent: GameEvent | null;
  resultText: string; decisions: Decision[];
  gameOver: boolean; survived: boolean; earlySale: boolean;
  outfit: OutfitConfig;
  historicalKnowledge: number;
  knowledgeLog: string[];
  triviaCounter: number;
  currentTrivia: TriviaQuestion | null;
  usedTriviaIds: Set<string>;
  triviaStreak: number;
  insight: number;
  objectives: Objective[];
  routeState: RouteState;
  routeTag: "SAFE" | "FAST" | "PROFIT";
  riskHintsOn: boolean;
  pendingChoiceIndex: number | null;
  pendingEventQuestion: EventGateQuestion | null;
  objectiveNotice: string;
  sageIndex: number;
  currentSage: SageEncounterData | null;
  sagesMet: string[];
  trailFeed: string[];
  hardPaceStreak: number;
}


// ═══════════════════════════════════════════════════════════════
// ANIMATED PRAIRIE SCENE 
// ═══════════════════════════════════════════════════════════════

function PrairieScene({ progress, pace }: { progress: number; pace: string; turn: number }) {
  const mappedPace = pace === "push" ? "push" : pace === "normal" ? "normal" : "rest";
  return <ChisholmParallaxBackground progress={progress} pace={mappedPace} />;
}

// ═══════════════════════════════════════════════════════════════
// OUTFIT SCREEN
// ═══════════════════════════════════════════════════════════════


function getCrewRating(herd: number, crew: number): { label: string; color: string; condition: number } {
  const ratio = herd / crew;
  if (ratio > 300) return { label: "Suicide run", color: "text-red-500", condition: 30 };
  if (ratio > 250) return { label: "Understaffed", color: "text-orange-400", condition: 40 };
  if (ratio > 200) return { label: "Tight", color: "text-yellow-400", condition: 52 };
  if (ratio > 150) return { label: "Solid", color: "text-emerald-400", condition: 62 };
  return { label: "Well-staffed", color: "text-blue-400", condition: 70 };
}

// Standard kit is no longer micro-managed at outfit — rifles, spare parts,
// trail teams, and crew wages come bundled at a fixed cost so the player
// only sizes the four things that matter: herd, crew, horses, provisions.
const FIXED_GUNS = 6;
const FIXED_SPAREPARTS = 3;
const FIXED_HORSEQUALITY = 2;
const FIXED_WAGES: "low" | "standard" | "good" = "standard";
const FIXED_GEAR_COST =
  FIXED_GUNS * COST_GUN +
  FIXED_SPAREPARTS * COST_SPAREPARTS +
  FIXED_HORSEQUALITY * COST_HORSE_QUALITY +
  WAGE_COST[FIXED_WAGES];

function OutfitScreen({ onDone }: { onDone: (config: OutfitConfig) => void }) {
  const [herdIdx, setHerdIdx] = useState(2); 
  const [extraCrew, setExtraCrew] = useState(4); 
  const [extraHorses, setExtraHorses] = useState(12); 
  const [extraSupplies, setExtraSupplies] = useState(10); 

  const herd = HERD_OPTIONS[herdIdx];
  const crew = BASE_CREW + extraCrew;
  const horses = BASE_HORSES + extraHorses;
  const supplies = BASE_SUPPLIES + extraSupplies;
  const spent = FIXED_GEAR_COST + extraCrew * COST_COWBOY + extraHorses * COST_HORSE + extraSupplies * COST_SUPPLY;
  const remaining = OUTFIT_BUDGET - spent;
  const rating = getCrewRating(herd, crew);
  const horsesPerCowboy = (horses / crew).toFixed(1);
  const potentialValue = herd * 40;

  return (
    <div className="west-app h-screen bg-stone-900 text-stone-100 flex flex-col overflow-hidden" style={{ fontFamily: "'Georgia', serif" }}>
      <div className="flex-shrink-0 bg-stone-800">
        <div className="max-w-4xl mx-auto">
          <PrairieScene progress={0} pace="easy" turn={0} />
        </div>
      </div>
      <div className="flex-1 min-h-0 overflow-y-auto p-3">
        <div className="max-w-lg mx-auto space-y-3">
          <div className="text-center">
            <h1 className="text-xl font-bold text-amber-400">SAN ANTONIO &mdash; SPRING 1867</h1>
            <p className="text-stone-400 text-xs mt-0.5">Outfit your drive. Budget: <span className={remaining >= 0 ? "text-emerald-400" : "text-red-500"}>${remaining.toLocaleString()}</span> of ${OUTFIT_BUDGET.toLocaleString()}</p>
          </div>

          <div className="bg-stone-800 border border-stone-700 rounded p-2.5">
            <div className="flex justify-between items-center text-xs mb-1">
              <span className="text-stone-300 font-bold">{"\uD83D\uDC02"} Herd Size</span>
              <span className="text-amber-400 font-mono">{herd.toLocaleString()} head</span>
            </div>
            <input type="range" min={0} max={4} value={herdIdx} onChange={e => setHerdIdx(+e.target.value)} className="w-full accent-amber-500 h-2" />
          </div>

          <div className="bg-stone-800 border border-stone-700 rounded p-2.5">
            <div className="flex justify-between items-center text-xs mb-1">
              <span className="text-stone-300 font-bold">{"\uD83E\uDD20"} Cowboys</span>
              <span className="font-mono">{crew} <span className="text-stone-500">({BASE_CREW} + {extraCrew} extra)</span></span>
            </div>
            <input type="range" min={0} max={10} value={extraCrew} onChange={e => setExtraCrew(+e.target.value)} className="w-full accent-amber-500 h-2" />
          </div>

          <div className="bg-stone-800 border border-stone-700 rounded p-2.5">
            <div className="flex justify-between items-center text-xs mb-1">
              <span className="text-stone-300 font-bold">{"\uD83D\uDC0E"} Horses</span>
              <span className="font-mono">{horses} <span className="text-stone-500">({BASE_HORSES} + {extraHorses})</span></span>
            </div>
            <input type="range" min={0} max={30} value={extraHorses} onChange={e => setExtraHorses(+e.target.value)} className="w-full accent-amber-500 h-2" />
          </div>

          <div className="bg-stone-800 border border-stone-700 rounded p-2.5">
            <div className="flex justify-between items-center text-xs mb-1">
              <span className="text-stone-300 font-bold">{"\uD83C\uDF56"} Provisions</span>
              <span className="font-mono">{supplies} <span className="text-stone-500">(+{extraSupplies})</span></span>
            </div>
            <input type="range" min={0} max={30} value={extraSupplies} onChange={e => setExtraSupplies(+e.target.value)} className="w-full accent-amber-500 h-2" />
            <p className="text-[10px] text-stone-500 mt-1">Food and medicine for the crew. Top up at towns along the trail.</p>
          </div>

          <div className="bg-stone-800/60 border border-stone-700 rounded p-2.5 text-[11px] text-stone-400">
            <div className="flex justify-between"><span className="font-bold text-stone-300">Standard kit (included)</span><span className="font-mono text-stone-400">${FIXED_GEAR_COST.toLocaleString()}</span></div>
            <p className="mt-0.5">Rifles &amp; ammo, spare parts, sound trail teams, and standard wages — bundled so you can focus on the four essentials above.</p>
          </div>

          <div className={`rounded p-2.5 border text-center ${remaining >= 0 ? "bg-stone-800 border-stone-700" : "bg-red-900/30 border-red-800"}`}>
            <div className="border-t border-stone-600 mt-1 pt-1 flex justify-between font-bold text-stone-200">
              <span>Remaining</span>
              <span className={remaining >= 0 ? "text-emerald-400" : "text-red-500"}>${remaining.toLocaleString()}</span>
            </div>
          </div>

          <button
            onClick={() => onDone({ herd, crew, horses, supplies, guns: FIXED_GUNS, spareParts: FIXED_SPAREPARTS, medicalGear: 0, horseQuality: FIXED_HORSEQUALITY, wages: FIXED_WAGES, budgetSpent: spent, startingCash: Math.max(0, remaining) })}
            disabled={remaining < 0}
            className={`w-full py-2.5 font-bold rounded transition-colors ${remaining >= 0 ? "bg-amber-700 hover:bg-amber-600 text-white" : "bg-stone-700 text-stone-500 cursor-not-allowed"}`}
          >
            {remaining < 0 ? "OVER BUDGET" : "HIT THE TRAIL"}
          </button>
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// ENGINE
// ═══════════════════════════════════════════════════════════════

function clamp(v:number,min=0,max=100){return Math.max(min,Math.min(max,v));}
function weightedPick<T extends{weight?:number}>(items:T[]):T{
  const total=items.reduce((s,i)=>s+(i.weight||1),0);let r=Math.random()*total;
  for(const item of items){r-=item.weight||1;if(r<=0)return item;}return items[0];
}

// ── Knowledge becomes a live capability ─────────────────────────
// historicalKnowledge + trivia streak collapse into a capped
// competence factor (0..~0.6). 30 knowledge ≈ "mastery" — the same
// scale getTrailGrade already uses. This is what makes "a student who
// knows the material dominates" real during play, not just at grading.
function competenceFactor(historicalKnowledge: number, streak: number): number {
  const k = Math.min(historicalKnowledge / 30, 1);
  const s = Math.min(streak * 0.03, 0.15);
  return Math.min(k * 0.5 + s, 0.6);
}

// Net desirability of an outcome's resource deltas. Crew is the
// scarcest, most consequential resource, so it dominates; herd count
// is the score you are ultimately graded on.
function outcomeFavorability(o: Outcome): number {
  const e = o.effects || {};
  return (e.herd || 0) * 1
    + (e.crew || 0) * 25
    + (e.horses || 0) * 3
    + (e.morale || 0) * 2
    + (e.supplies || 0) * 2
    + (e.herdCondition || 0) * 2
    + (e.wagonCondition || 0) * 1.5
    + (e.cash || 0) * 0.2;
}

// State + knowledge biased outcome roll (interlock). With no skill the
// pick is the original pure-random weightedPick. As competence and
// situational readiness rise, weight tilts toward the more favorable
// outcomes — so the same risky choice rewards a prepared, knowledgeable
// player and punishes an unprepared one, instead of being a coin flip.
function biasedPick(outcomes: Outcome[], comp: number, readiness: number): Outcome {
  if (outcomes.length <= 1) return outcomes[0];
  const skill = Math.min(comp + (readiness - 0.5) * 0.4, 0.85);
  if (skill <= 0) return weightedPick(outcomes);
  const favs = outcomes.map(outcomeFavorability);
  const min = Math.min(...favs);
  const span = (Math.max(...favs) - min) || 1;
  const adjusted = outcomes.map((o, i) => {
    const norm = (favs[i] - min) / span;            // 0 worst … 1 best
    const factor = 1 + skill * (norm - 0.5) * 2;    // skill .85 → ~[0.15 … 1.85]
    return { ...o, weight: Math.max(0.05, (o.weight || 1) * factor) };
  });
  return weightedPick(adjusted);
}

// Situational readiness (0..1) from the resources that govern how well
// the outfit absorbs a gamble: herd condition, crew strength, wagon.
function readinessOf(resources: Resources): number {
  return clamp(
    (resources.herdCondition / 100 + Math.min(resources.crew / 12, 1) + resources.wagonCondition / 100) / 3,
    0, 1,
  );
}

function routeAdjustedEvent(day:number,totalDays:number,used:Set<string>,events:GameEvent[],routeTag:"SAFE"|"FAST"|"PROFIT"){
  const base = pickEvent(day,totalDays,used,events);
  if (!base) return null;
  const phase = day / totalDays;
  const pool = events.filter(e => phase >= e.phase_min && phase <= e.phase_max && !used.has(e.id));
  if (pool.length === 0) return base;
  const withWeights = pool.map(e => {
    const danger = e.id.includes("storm") || e.id.includes("stampede") || e.id.includes("fire") || e.id.includes("rustler") || e.id.includes("fever") || e.id.includes("snake");
    const market = e.id.includes("buyer") || e.id.includes("competition") || e.id.includes("good_grass");
    let weight = e.weight;
    if (routeTag === "SAFE" && danger) weight = Math.max(1, weight - 2);
    if (routeTag === "FAST" && danger) weight += 2;
    if (routeTag === "PROFIT" && market) weight += 2;
    return { ...e, weight };
  });
  return weightedPick(withWeights);
}

function shouldGateTrivia(eventId: string, turn: number){
  // Only gate a choice behind a question on genuinely high-risk events,
  // and only on some of those, so the question feels earned rather than
  // a constant tax on every interaction.
  const danger = /storm|stampede|fire|rustler|fever|snake|raid|flood|drought/.test(eventId);
  if (!danger) return false;
  return (eventId.length + turn) % 2 === 0;
}
function resolveChoice(ch:Choice, comp = 0, readiness = 0.5):{effects?:Resources;result?:string;earlyEnd?:boolean}{
  if(ch.outcomes)return biasedPick(ch.outcomes, comp, readiness);return{effects:ch.effects,result:ch.result,earlyEnd:ch.earlyEnd};
}
function pickEvent(day:number,td:number,used:Set<string>,evts:GameEvent[]):GameEvent|null{
  const p=day/td;const el=evts.filter(e=>p>=e.phase_min&&p<=e.phase_max&&!used.has(e.id));
  const pool=el.length>0?el:evts.filter(e=>p>=e.phase_min&&p<=e.phase_max);
  if(!pool.length)return null;return weightedPick(pool);
}
// ═══════════════════════════════════════════════════════════════
// ALL 17 EVENTS — imported from campaigns/chisholm/events.ts
// ═══════════════════════════════════════════════════════════════


// ═══════════════════════════════════════════════════════════════
// CONSTANTS & HELPERS
// ═══════════════════════════════════════════════════════════════

function getGrade2(h:number,started:number,s:boolean):string{if(!s)return"F";const p=h/started;if(p>=0.95)return"A";if(p>=0.88)return"B";if(p>=0.80)return"C";if(p>=0.70)return"D";return"F";}
const GC:Record<string,string>={"A+":"text-amber-300",A:"text-emerald-400",B:"text-blue-400",C:"text-yellow-400",D:"text-orange-400",F:"text-red-500"};
// Once a player has learned enough, sage risk hints come for free —
// knowledge grants foresight, instead of paying insight on every event.
const FORESIGHT_KNOWLEDGE = 12;
const DEFAULT_OUTFIT: OutfitConfig = { herd: 2500, crew: 12, horses: 60, supplies: 65, guns: 4, spareParts: 3, medicalGear: 2, horseQuality: 2, wages: "standard", budgetSpent: 0, startingCash: 0 };

// Human labels for the town trading post.
const TRADE_LABELS: Record<string, string> = {
  cash: "cash", supplies: "provisions", horses: "horses", spareParts: "spare parts",
  ammo: "ammo", herd: "cattle", crew: "crew", morale: "morale", wagonCondition: "wagon",
};
const makeInit=():GameState=>({day:1,turn:0,resources:{...INIT_R},phase:"intro",pace:"normal",distance:0,currentEvent:null,resultText:"",decisions:[],gameOver:false,survived:false,earlySale:false,outfit:{...DEFAULT_OUTFIT},historicalKnowledge:0,knowledgeLog:[],triviaCounter:0,currentTrivia:null,usedTriviaIds:new Set(),triviaStreak:0,insight:1,objectives:[],routeState:{currentNodeId:"start"},routeTag:"SAFE",riskHintsOn:false,pendingChoiceIndex:null,pendingEventQuestion:null,objectiveNotice:"",sageIndex:0,currentSage:null,sagesMet:[],trailFeed:[ChisholmCampaign.trailFeedOpener],hardPaceStreak:0});

// ═══════════════════════════════════════════════════════════════
// APP
// ═══════════════════════════════════════════════════════════════

export default function App(){
  const[campaignId,setCampaignId]=useState<string|null>(null);
  const[state,setState]=useState<GameState>(makeInit());
  const[usedEvents,setUsedEvents]=useState<Set<string>>(new Set());
  const[isTeacherMode, setIsTeacherMode]=useState(false);
  // Final-exam gate. The end-screen results stay locked until the
  // player passes the TEKS check for understanding.
  const[examPassed,setExamPassed]=useState(false);
  const[examScore,setExamScore]=useState(0);
  const[showLog,setShowLog]=useState(false);
  // Name of the last supply town the player chose to leave, so the auto-
  // advance loop doesn't re-stop at the same town every step.
  const[leftTownId,setLeftTownId]=useState<string|null>(null);

  const start=useCallback(()=>{setState({...makeInit(),phase:"outfit"});setUsedEvents(new Set());setExamPassed(false);setExamScore(0);setLeftTownId(null);},[]);
  const backToMenu=useCallback(()=>{setCampaignId(null);setState(makeInit());setUsedEvents(new Set());setExamPassed(false);setExamScore(0);setLeftTownId(null);},[]);

  // ── Game Juice ──────────────────────────────────────────────
  const { floats, spawn: spawnFloat } = useFloatingNumbers();
  const { shakeClass, shake } = useScreenShake();
  const { pulses, pulse } = useStatPulse();

  const onDelta = useCallback((key: string, delta: number) => {
    const label = RESOURCE_LABELS[key];
    if (!label) return;
    pulse(key, delta > 0 ? "gain" : "loss");
    spawnFloat(delta, label);
  }, [pulse, spawnFloat]);

  const onBigHit = useCallback((totalLoss: number) => {
    if (totalLoss > 100) shake("heavy");
    else if (totalLoss > 30) shake("medium");
    else shake("light");
  }, [shake]);

  useResourceTracker(state.resources, { onDelta, onBigHit });

  const onOutfitDone=useCallback((config:OutfitConfig)=>{
    setState(prev=>{
      const rating=getCrewRating(config.herd,config.crew);
      const morale=WAGE_MORALE[config.wages];
      return{...prev,
        phase:"sailing"as const,
        outfit:config,
        trailFeed:["You roll out of San Antonio with fresh teams and a strict ledger."],
        hardPaceStreak:0,
        resources:{
          herd:config.herd,
          crew:config.crew,
          horses:config.horses,
          supplies:config.supplies,
          morale,
          herdCondition:rating.condition,
          ammo:config.guns*10,
          spareParts:config.spareParts,
          wagonCondition:clampR("wagonCondition", 56 + config.spareParts * 6 + config.horseQuality * 6),
          cash:config.startingCash,
        },
      };
    });
  },[]);

  const advanceTurn=useCallback(()=>{
    setState(prev=>{
      const s:GameState={...prev,resources:{...prev.resources}};
      const before = { turn: prev.turn, day: prev.day, distance: prev.distance, resources: { ...prev.resources } };
      s.turn+=1;const pace=PACES.find(p=>p.id===s.pace)!;
      s.day=Math.min(s.day+DAYS_PER_TURN,TOTAL_DAYS+1);
      for(const[k,v]of Object.entries(pace.fx))s.resources[k]=clampR(k,(s.resources[k]||0)+v);
      if (s.routeTag === "FAST") {
        s.resources.herdCondition = clampR("herdCondition", s.resources.herdCondition - 2);
        s.resources.wagonCondition = clampR("wagonCondition", s.resources.wagonCondition - 3);
      }
      if (s.routeTag === "SAFE") s.resources.morale = clampR("morale", s.resources.morale + 1);
      if (s.routeTag === "PROFIT") s.resources.supplies = clampR("supplies", s.resources.supplies - 1);

      // Crew shortages throttle pace and herd control
      const crewPenalty = s.resources.crew <= 5 ? 0.6 : s.resources.crew <= 7 ? 0.78 : s.resources.crew <= 9 ? 0.9 : 1;
      const wagonPenalty = s.resources.wagonCondition <= 0 ? 0.45 : s.resources.wagonCondition < 20 ? 0.7 : s.resources.wagonCondition < 40 ? 0.85 : 1;
      const distanceGain = pace.mpd * DAYS_PER_TURN * crewPenalty * wagonPenalty;
      s.distance=Math.min(s.distance+distanceGain,TOTAL_DISTANCE);
      s.hardPaceStreak = pace.id === "push" ? s.hardPaceStreak + 1 : Math.max(0, s.hardPaceStreak - 1);

      const crewDrain = Math.ceil(s.resources.crew / 8);
      const wagonLossDrain = s.resources.wagonCondition <= 0 ? 7 : 0;
      s.resources.supplies=clamp(s.resources.supplies-crewDrain-wagonLossDrain,0,100);

      // Competence (knowledge + streak) softens this turn's attrition.
      const comp = competenceFactor(s.historicalKnowledge, s.triviaStreak);

      // Wagon stress model. Weather is now mostly driven by pace and how
      // worn the wagon already is, with only a small random jitter —
      // texture, not stakes.
      const supplyStress = s.resources.supplies < 22 ? 5 : s.resources.supplies < 35 ? 3 : 0;
      const herdStress = s.resources.herdCondition < 30 ? 3 : 0;
      const hardPaceStress = s.pace === "push" ? 6 : s.pace === "normal" ? 2 : 0;
      const weatherBase = (s.pace === "push" ? 3 : s.pace === "normal" ? 1.5 : 0.5) + (s.resources.wagonCondition < 40 ? 2 : 0);
      const weatherStress = Math.round(weatherBase + Math.random() * 1.5);
      const totalWagonStress = supplyStress + herdStress + hardPaceStress + weatherStress;
      s.resources.wagonCondition = clampR("wagonCondition", s.resources.wagonCondition - totalWagonStress + Math.floor((s.outfit.horseQuality || 0) / 2));

      // Breakdowns and spare parts consequences
      const breakdownRisk = (s.pace === "push" ? 0.22 : s.pace === "normal" ? 0.12 : 0.06) + (s.resources.wagonCondition < 35 ? 0.1 : 0) + (s.resources.spareParts <= 0 ? 0.12 : 0);
      if (Math.random() < breakdownRisk) {
        if (s.resources.spareParts > 0) {
          s.resources.spareParts = clampR("spareParts", s.resources.spareParts - 1);
          s.resources.wagonCondition = clampR("wagonCondition", s.resources.wagonCondition + 12);
          s.resources.supplies = clampR("supplies", s.resources.supplies - 4);
          s.resultText = "Wagon axle strain forced a field repair. You burned one spare-part crate and lost time.";
          s.phase = "result";
        } else {
          s.resources.wagonCondition = clampR("wagonCondition", s.resources.wagonCondition - 20);
          s.resources.supplies = clampR("supplies", s.resources.supplies - 12);
          s.resources.herdCondition = clampR("herdCondition", s.resources.herdCondition - 6);
          // Abandonment is state-driven, not a blind roll: the wagon is
          // lost only when it was already gutted before this breakdown.
          if (s.resources.wagonCondition <= 8) {
            s.resources.wagonCondition = 0;
            s.resultText = "No spare parts. The chuck wagon was abandoned in mud and broken timber. You are now hauling what you can on horseback.";
          } else {
            s.resultText = "No spare parts. The wagon limps onward, badly damaged, with food and medical stores spilling out.";
          }
          s.phase = "result";
        }
      }

      // Consequential failures under weak conditions. Loss size now
      // scales with how far below the safe threshold the outfit sits
      // (learnable), carries only light jitter, and competence softens it.
      const soften = 1 - comp * 0.5; // up to ~30% less attrition at mastery
      if (s.resources.herdCondition < 35) {
        const deficit = 35 - s.resources.herdCondition;                 // 0..35
        const base = deficit * 1.8 + (s.resources.herdCondition < 20 ? 25 : 0);
        const loss = Math.round((base + Math.random() * 10) * soften);
        s.resources.herd = Math.max(0, s.resources.herd - loss);
      }
      if (s.resources.crew <= 7) {
        const loss = Math.round(((8 - s.resources.crew) * 4 + Math.random() * 6) * soften);
        s.resources.herd = Math.max(0, s.resources.herd - loss);
      }
      // Desertion is now a consequence of compounding neglect rather than
      // a per-turn coin flip: morale AND supplies both failing, or either
      // one in true collapse, costs a hand.
      if ((s.resources.morale < 20 && s.resources.supplies < 15) || s.resources.morale < 12 || s.resources.supplies < 8) {
        s.resources.crew = Math.max(0, s.resources.crew - 1);
      }

      const turnFeed = buildTrailFeedEntries(s.resources, pace.id, s.hardPaceStreak, distanceGain, s.day);
      if (isNearSupplyTown((s.distance / TOTAL_DISTANCE) * 100).near) {
        turnFeed.push("A town is close ahead. Repairs and fresh hands are available for a high price.");
      }
      s.trailFeed = [...s.trailFeed, ...turnFeed].slice(-18);
      if(s.resources.crew<=2||s.resources.herd<=100||s.resources.horses<=5)return{...s,phase:"end"as const,gameOver:true,survived:false};
      if(s.distance>=TOTAL_DISTANCE)return{...s,phase:"end"as const,gameOver:true,survived:true};
      const tick = tickObjectives(s.objectives, before, { turn: s.turn, day: s.day, distance: s.distance, resources: { ...s.resources } });
      s.objectives = tick.active;
      if (tick.completedNow.length > 0) {
        const first = tick.completedNow[0];
        s.insight += first.reward.insight;
        for (const completed of tick.completedNow) {
          if (completed.reward.resources) {
            for (const [k, v] of Object.entries(completed.reward.resources)) {
              s.resources[k] = clampR(k, (s.resources[k] || 0) + v);
            }
          }
        }
        s.objectiveNotice = `Objective Complete! ${first.title} (+${first.reward.insight} Insight)`;
      }
      if (s.turn % 3 === 0 && s.objectives.length < 2) {
        s.objectives = [...s.objectives, generateObjective({ turn: s.turn, day: s.day, distance: s.distance, resources: s.resources })];
      }

      // ── SAGE CHECK — fires before any random event ────
      const currentProgress = (s.distance / TOTAL_DISTANCE) * 100;
      const prevProgress = (before.distance / TOTAL_DISTANCE) * 100;
      if (s.sageIndex < SAGES.length) {
        const nextSage = SAGES[s.sageIndex];
        if (currentProgress >= nextSage.threshold) {
          s.currentSage = nextSage;
          s.phase = "sage";
          console.log(`[SAGE] Triggered: ${nextSage.name} at ${currentProgress.toFixed(1)}% (threshold: ${nextSage.threshold}%)`);
          return s;
        }
      }

      const event=routeAdjustedEvent(s.day,TOTAL_DAYS,usedEvents,EVENTS,s.routeTag);
      console.log(`[ADVANCE] Turn ${s.turn} | Day ${s.day} | Event: ${event?.id || 'NONE'} | TriviaCounter: ${s.triviaCounter}`);
      if(event){
        if (s.triviaCounter >= 3) {
          const progress = Math.min((s.distance / TOTAL_DISTANCE) * 100, 100);
          const trivia = pickTriviaQuestion(progress, s.usedTriviaIds);
          console.log(`[TRIVIA CHECK] Counter=${s.triviaCounter} | Progress=${progress.toFixed(1)}% | Question found: ${trivia?.id || 'NULL'}`);
          if (trivia) {
            s.currentTrivia = trivia;
            s.usedTriviaIds = new Set(s.usedTriviaIds).add(trivia.id);
            s.triviaCounter = 0;
            s.phase = "trivia";
            console.log(`[TRIVIA FIRES] Question: ${trivia.id} | Phase set to 'trivia'`);
            return s;
          }
        }
        setUsedEvents(p=>new Set(p).add(event.id));s.currentEvent={...event,triviaGate:shouldGateTrivia(event.id,s.turn)};s.phase="event";
        s.riskHintsOn = false;
        s.pendingChoiceIndex = null;
        s.pendingEventQuestion = null;
        s.triviaCounter++;
        console.log(`[EVENT] ${event.id} | Counter now: ${s.triviaCounter}`);
      }
      return s;
    });
  },[usedEvents]);

  const chooseRoute = useCallback((toId: string, tag: "SAFE"|"FAST"|"PROFIT") => {
    setState(prev => ({ ...prev, routeState: { currentNodeId: toId }, routeTag: tag }));
  }, []);

  const finalizeChoice=useCallback((ci:number,insightBonus:number)=>{
    setState(prev=>{
      if(!prev.currentEvent || !prev.currentEvent.choices) return prev;
      const s:GameState={...prev,resources:{...prev.resources},decisions:[...prev.decisions]};
      const comp=competenceFactor(s.historicalKnowledge,s.triviaStreak);
      const readiness=readinessOf(s.resources);
      const choice=s.currentEvent!.choices![ci];const outcome=resolveChoice(choice,comp,readiness);
      {
        const ev=s.currentEvent!;
        const fact=Array.isArray(ev.trivia)&&ev.trivia.length?`Did you know? ${ev.trivia[0]}`:"";
        s.decisions.push({
          event:ev.title,
          choice:choice.text,
          day:s.day,
          text:ev.text,
          detail:[outcome.result,fact].filter(Boolean).join("\n\n")||undefined,
        });
      }
      if(outcome.effects)for(const[k,v]of Object.entries(outcome.effects))if(s.resources[k]!==undefined){
        let delta = v;
        if (k === "herd" && v < 0 && s.resources.crew <= 7) delta = Math.floor(v * 1.35);
        if (k === "supplies" && v < 0 && s.resources.wagonCondition <= 20) delta = Math.floor(v * 1.3);
        s.resources[k]=clampR(k,s.resources[k]+delta);
      }
      if (insightBonus > 0) s.insight += insightBonus;
      if(choice.earlyEnd||outcome.earlyEnd)s.earlySale=true;
      if (insightBonus > 0) {
        s.resultText=`${outcome.result||""}\n\nYou answered the trivia correctly and gained +${insightBonus} Insight.`;
      } else {
        s.resultText=outcome.result||"";
      }
      s.phase="result";
      s.pendingChoiceIndex = null;
      s.pendingEventQuestion = null;
      return s;
    });
  },[]);

  // Handle standard Visual Novel Choice
  const handleChoice=useCallback((ci:number)=>{
    if (state.currentEvent?.triviaGate) {
      const q = CHISHOLM_EVENT_TRIVIA[(state.turn + ci) % CHISHOLM_EVENT_TRIVIA.length];
      setState(prev => ({ ...prev, phase: "event_trivia", pendingChoiceIndex: ci, pendingEventQuestion: q }));
      return;
    }
    finalizeChoice(ci, 0);
  },[finalizeChoice, state.currentEvent?.triviaGate, state.turn]);

  const handleEventTriviaAnswer = useCallback((choiceIndex:number)=>{
    const q = state.pendingEventQuestion;
    const pendingChoiceIndex = state.pendingChoiceIndex;
    if (!q || pendingChoiceIndex === null) return;
    const correct = choiceIndex === q.correctIndex;
    finalizeChoice(pendingChoiceIndex, correct ? 1 : 0);
  },[state.pendingEventQuestion,state.pendingChoiceIndex,finalizeChoice]);

  const spendInsightForHints = useCallback(() => {
    setState(prev => {
      if (prev.insight <= 0 || prev.riskHintsOn) return prev;
      return { ...prev, insight: prev.insight - 1, riskHintsOn: true };
    });
  }, []);

  // 🔴 Handle Push Your Luck Update (Realtime Resource Adjustment)
  const handlePushUpdate = useCallback((effects: Resources) => {
    setState(prev => {
      const s: GameState = { ...prev, resources: { ...prev.resources } };
      for (const [k, v] of Object.entries(effects)) {
        if (s.resources[k] !== undefined) s.resources[k] = clampR(k, s.resources[k] + v);
      }
      return s;
    });
  }, []);

  // 🔴 Handle leaving the Push Your Luck state
  const handlePushLeave = useCallback((log: string[]) => {
    setState(prev => {
      if (!prev.currentEvent) return prev;
      const s: GameState = { ...prev, decisions: [...prev.decisions] };
      s.decisions.push({ event: s.currentEvent!.title, choice: `Pushed luck ${log.length - 1} times.`, day: s.day, text: s.currentEvent!.text });
      s.currentEvent = null;
      s.phase = "sailing";
      return s;
    });
  }, []);

  const continueGame=useCallback(()=>{
    setState(prev=>{
      const s:GameState={...prev,currentEvent:null,resultText:"",objectiveNotice:""};
      if(s.resources.crew<=2||s.resources.herd<=100||s.resources.horses<=5)return{...s,phase:"end"as const,gameOver:true,survived:false};
      if(s.distance>=TOTAL_DISTANCE||s.earlySale)return{...s,phase:"end"as const,gameOver:true,survived:true};
      s.phase="sailing";return s;
    });
  },[]);

  const handleSageComplete = useCallback((correct: boolean) => {
    setState(prev => {
      if (!prev.currentSage) return prev;
      const s: GameState = {
        ...prev,
        resources: { ...prev.resources },
        decisions: [...prev.decisions],
        knowledgeLog: [...prev.knowledgeLog],
        sagesMet: [...prev.sagesMet],
      };
      const sage = s.currentSage!;
      const reward = correct ? sage.reward.correct : sage.reward.wrong;
      const knowledge = correct ? sage.reward.knowledgeCorrect : sage.reward.knowledgeWrong;

      // Apply resource rewards
      for (const [k, v] of Object.entries(reward)) {
        if (k === "insight") {
          s.insight += v;
        } else if (s.resources[k] !== undefined) {
          s.resources[k] = clampR(k, s.resources[k] + v);
        }
      }

      // Apply knowledge
      s.historicalKnowledge += knowledge;
      s.knowledgeLog.push(`${sage.name}: +${knowledge} knowledge${correct ? " (correct)" : ""}`);
      s.decisions.push({
        event: `Sage: ${sage.name}`,
        choice: correct ? `Answered correctly` : `Learned from ${sage.name}`,
        day: s.day,
        text: sage.question.question,
        detail: `Correct answer: ${sage.question.choices[sage.question.correctIndex]}\n\n${sage.question.explanation}`,
      });

      // Advance sage index and record the meeting
      s.sagesMet.push(sage.id);
      s.sageIndex = prev.sageIndex + 1;
      s.currentSage = null;
      s.phase = "sailing";

      return s;
    });
  }, []);

  const handleHunt=useCallback(()=>{
    setState(prev=>{
      const s:GameState={...prev,resources:{...prev.resources},decisions:[...prev.decisions]};
      const ammo=s.resources.ammo||0;
      if(ammo<5)return s; // shouldn't happen, button is hidden
      s.resources.ammo=ammo-5;
      const gunBonus=Math.min(s.outfit.guns,8);
      const roll=Math.random()*100;
      const nothingCeil=35-gunBonus;
      const scrapsCeil=55-gunBonus*0.5;
      const decentCeil=75;
      const greatCeil=90;
      const accidentCeil=97;

      let result:string;
      if(roll<nothingCeil){result="You find no game and use five rounds of ammo.";}
      else if(roll<scrapsCeil){s.resources.supplies=clampR("supplies",s.resources.supplies+2);result="You catch small game, but food gains are low.";}
      else if(roll<decentCeil){s.resources.supplies=clampR("supplies",s.resources.supplies+7);result="A whitetail deer. Crew eats well tonight.";}
      else if(roll<greatCeil){s.resources.supplies=clampR("supplies",s.resources.supplies+14);result="You bring in a full buffalo. The crew has food for days.";}
      else if(roll<accidentCeil){s.resources.horses=Math.max(0,s.resources.horses-1);result="Horse stepped in a prairie dog hole at a gallop. Had to put the animal down.";}
      else{s.resources.crew=Math.max(0,s.resources.crew-1);result="A hunter caught a rattlesnake bite reaching through brush.";}
      s.decisions.push({event:"Hunting",choice:"Went hunting",day:s.day,detail:result});
      s.resultText=result;s.phase="result";return s;
    });
  },[]);

  // Trapping — ammo-free, lower yield, no accidents. The safe, slow way
  // to add food; pairs with hunting (high risk/reward) for some autonomy.
  const handleTrap = useCallback(()=>{
    setState(prev=>{
      const s:GameState={...prev,resources:{...prev.resources},decisions:[...prev.decisions]};
      const roll=Math.random()*100;
      let result:string;
      if(roll<38){result="The snares come up empty this time.";}
      else if(roll<80){s.resources.supplies=clampR("supplies",s.resources.supplies+3);result="Rabbits and a few birds in the snares — a small, steady haul.";}
      else{s.resources.supplies=clampR("supplies",s.resources.supplies+6);result="A good night for the traps. Enough small game to stretch the larder.";}
      s.decisions.push({event:"Trapping",choice:"Set snares for small game",day:s.day,detail:result});
      s.resultText=result;s.phase="result";return s;
    });
  },[]);

  // Town barter: apply a give → get trade. Used by the Trading Post for
  // both cash purchases and bartering surplus inventory.
  const handleTrade = useCallback((offer: TradeOffer, townName: string) => {
    setState(prev => {
      const s: GameState = { ...prev, resources: { ...prev.resources }, decisions: [...prev.decisions] };
      for (const [k, v] of Object.entries(offer.give)) if ((s.resources[k] || 0) < v) return prev;
      for (const [k, v] of Object.entries(offer.give)) s.resources[k] = clampR(k, (s.resources[k] || 0) - v);
      for (const [k, v] of Object.entries(offer.get)) s.resources[k] = clampR(k, (s.resources[k] || 0) + v);
      const note = `${offer.label} at ${townName}.`;
      s.decisions.push({ event: `Trade — ${townName}`, choice: offer.label, day: s.day, detail: note });
      s.resultText = note;
      s.phase = "result";
      return s;
    });
  }, []);

  const handleTownRepair = useCallback(() => {
    setState(prev => {
      if (prev.resources.cash < 140) return prev;
      const s: GameState = { ...prev, resources: { ...prev.resources }, decisions: [...prev.decisions], resultText: "" };
      s.resources.cash = clampR("cash", s.resources.cash - 140);
      s.resources.wagonCondition = clampR("wagonCondition", s.resources.wagonCondition + 28);
      s.resources.spareParts = clampR("spareParts", s.resources.spareParts + 1);
      s.decisions.push({ event: "Town Stop", choice: "Paid for blacksmith wagon repair", day: s.day, detail: "You paid steep town rates for blacksmith work and one spare-part crate." });
      s.resultText = "You paid steep town rates for blacksmith work and one spare-part crate.";
      s.trailFeed = [...(s.trailFeed || []), "Blacksmith repairs finished by lantern light. The wagon sounds steadier."].slice(-18);
      s.phase = "result";
      return s;
    });
  }, []);

  const handleTownHire = useCallback(() => {
    setState(prev => {
      if (prev.resources.cash < 110) return prev;
      const s: GameState = { ...prev, resources: { ...prev.resources }, decisions: [...prev.decisions], resultText: "" };
      s.resources.cash = clampR("cash", s.resources.cash - 110);
      s.resources.crew = clampR("crew", s.resources.crew + 1);
      s.resources.morale = clampR("morale", s.resources.morale + 4);
      s.decisions.push({ event: "Town Stop", choice: "Hired replacement hand", day: s.day, detail: "You hired a replacement hand at inflated trail-town wages." });
      s.resultText = "You hired a replacement hand at inflated trail-town wages.";
      s.trailFeed = [...(s.trailFeed || []), "A new hand joined at town. Camp duty and night watch improved."].slice(-18);
      s.phase = "result";
      return s;
    });
  }, []);

  const handleTownResupply = useCallback(() => {
    setState(prev => {
      if (prev.resources.cash < 95) return prev;
      const s: GameState = { ...prev, resources: { ...prev.resources }, decisions: [...prev.decisions], resultText: "" };
      s.resources.cash = clampR("cash", s.resources.cash - 95);
      s.resources.supplies = clampR("supplies", s.resources.supplies + 20);
      s.resources.morale = clampR("morale", s.resources.morale + 3);
      s.decisions.push({ event: "Town Stop", choice: "Bought provisions and medicine", day: s.day, detail: "You bought costly trail provisions, enough to steady the camp for now." });
      s.resultText = "You bought costly trail provisions, enough to steady the camp for now.";
      s.trailFeed = [...(s.trailFeed || []), "Fresh provisions reached camp. Meals should hold for several more days."].slice(-18);
      s.phase = "result";
      return s;
    });
  }, []);

  const handleTriviaComplete = useCallback((correct: boolean, effects: Record<string, number>) => {
    console.log(`[TRIVIA COMPLETE] Correct: ${correct} | Effects:`, effects);
    setState(prev => {
      const s: GameState = { ...prev, resources: { ...prev.resources }, knowledgeLog: [...prev.knowledgeLog], decisions: [...prev.decisions] };
      const qText = s.currentTrivia?.question || "Trivia";
      const tq = s.currentTrivia;
      const triviaDetail = tq
        ? `Correct answer: ${tq.choices[tq.correctIndex]}\n\n${tq.explanation}`
        : undefined;

      if (correct) {
        s.triviaStreak++;
        for (const [k, v] of Object.entries(effects)) {
          if (k === "historicalKnowledge") {
            s.historicalKnowledge += v;
            s.knowledgeLog.push(`Sage's Wisdom: +${v}`);
          } else if (k === "shortcut") {
            s.distance = Math.min(s.distance + v, TOTAL_DISTANCE);
          } else if (s.resources[k] !== undefined) {
            s.resources[k] = clampR(k, s.resources[k] + v);
          }
        }
        s.decisions.push({ event: "Sage Encounter", choice: `✓ Answered correctly (streak: ${s.triviaStreak}): "${qText}"`, day: s.day, text: qText, detail: triviaDetail });
      } else {
        s.triviaStreak = 0;
        s.decisions.push({ event: "Sage Encounter", choice: `Learned from: "${qText}"`, day: s.day, text: qText, detail: triviaDetail });
      }

      s.currentTrivia = null;
      s.phase = "sailing";

      if (s.distance >= TOTAL_DISTANCE) {
        return { ...s, phase: "end" as const, gameOver: true, survived: true };
      }
      return s;
    });
  }, []);

  const r=state.resources;
  const progress=state.distance/TOTAL_DISTANCE*100;
  const currentRouteNode = findNode(CHISHOLM_ROUTE, state.routeState.currentNodeId) || CHISHOLM_ROUTE[0];
  const supplyTown = isNearSupplyTown(progress);

  // ── Decision-driven progression ──────────────────────────────
  // There is no "advance turn" button. While on the trail, the drive moves
  // forward on its own until it reaches something the player must decide:
  // a route fork, a town stop, or a lost wagon. Events, sages, and trivia
  // (set by advanceTurn) pause it too, since the phase leaves "sailing".
  const atRouteFork = currentRouteNode.edges.length >= 2;
  const atTownStop = supplyTown.near && supplyTown.town !== leftTownId;
  const wagonLost = r.wagonCondition <= 0;
  const awaitingDecision = atRouteFork || atTownStop || wagonLost;
  useEffect(() => {
    if (state.phase !== "sailing" || state.gameOver || awaitingDecision) return;
    // Small delay so each leg of travel is visible (marker moves, feed updates).
    const t = setTimeout(() => advanceTurn(), 650);
    return () => clearTimeout(t);
  }, [state.phase, state.turn, state.gameOver, awaitingDecision, advanceTurn]);
  const wagonState = r.wagonCondition <= 0 ? "lost" : r.wagonCondition < 20 ? "critical" : r.wagonCondition < 40 ? "damaged" : r.wagonCondition < 65 ? "strained" : "operational";
  const warningFlags = [
    r.crew <= 7 ? "⚠️ Crew undermanned: herd control and security are deteriorating." : null,
    r.spareParts <= 0 ? "⚠️ No spare parts: next wagon failure could force abandonment." : null,
    r.wagonCondition < 35 ? `⚠️ Wagon ${wagonState}: travel and recovery options are collapsing.` : null,
    r.supplies < 20 ? "⚠️ Supplies unsustainable: illness, desertion, and herd losses likely." : null,
    r.morale < 20 ? "⚠️ Morale collapse risk: desertion likely in the next bad event." : null,
  ].filter(Boolean) as string[];
  const riskHints = (state.currentEvent?.choices || []).map((choice) => {
    if (choice.outcomes) {
      const avgLoss = choice.outcomes.reduce((sum, o) => sum + ((o.effects.herd || 0) < 0 ? Math.abs(o.effects.herd || 0) : 0) + ((o.effects.crew || 0) < 0 ? 20 : 0) + ((o.effects.morale || 0) < 0 ? Math.abs(o.effects.morale || 0) : 0), 0) / choice.outcomes.length;
      if (avgLoss > 70) return "HIGH";
      if (avgLoss > 30) return "MED";
      return "LOW";
    }
    const herdLoss = Math.abs(Math.min(0, choice.effects?.herd || 0));
    const moraleLoss = Math.abs(Math.min(0, choice.effects?.morale || 0));
    const crewLoss = Math.abs(Math.min(0, choice.effects?.crew || 0));
    const score = herdLoss + moraleLoss + crewLoss * 20;
    if (score > 70) return "HIGH";
    if (score > 30) return "MED";
    return "LOW";
  });
  console.log(`[RENDER] Phase: ${state.phase} | TriviaCounter: ${state.triviaCounter} | HasTrivia: ${!!state.currentTrivia}`);
  const partyMembers = getPartyMembers(r);

  const campaigns = [
    { id: "chisholm", title: "🐂 Chisholm Trail — 1867", subtitle: "San Antonio to Abilene", config: ChisholmCampaign, color: "bg-amber-800 hover:bg-amber-700", subColor: "text-amber-300" },
    { id: "silkroad", title: "🐫 Silk Road — 130 BCE", subtitle: "Chang'an to Constantinople", config: { isPublished: true }, color: "bg-indigo-900 hover:bg-indigo-800", subColor: "text-indigo-300" },
    { id: "crusades", title: "✝ Third Crusade — 1190", subtitle: "Warwick to Jerusalem", config: CrusadesCampaign, color: "bg-red-900 hover:bg-red-800", subColor: "text-red-300" },
    { id: "lewisclark", title: "🧭 Lewis & Clark — 1804", subtitle: "St. Louis to the Pacific", config: { isPublished: true }, color: "bg-emerald-900 hover:bg-emerald-800", subColor: "text-emerald-300" },
    { id: "joseph", title: "📖 Joseph — Reconstruction", subtitle: "A freedman's first free year (flag test)", config: josephReconstruction, color: "bg-stone-700 hover:bg-stone-600", subColor: "text-stone-300" },
    { id: "narrative-meiji", title: "🗾 Meiji Restoration — 1868", subtitle: "A young samurai, the old world ending (narrative product)", config: narrativeDemo, color: "bg-rose-900 hover:bg-rose-800", subColor: "text-rose-300" },
    { id: "branch-1812", title: "📜 Branching: War of 1812", subtitle: "Caleb Wren — new story engine", config: branching1812, color: "bg-sky-900 hover:bg-sky-800", subColor: "text-sky-300" },
    { id: "branch-reconstruction", title: "📜 Branching: Reconstruction", subtitle: "Tessa — new story engine", config: branchingReconstruction, color: "bg-sky-900 hover:bg-sky-800", subColor: "text-sky-300" },
    { id: "branch-suffrage", title: "📜 Branching: Women's Suffrage", subtitle: "Lottie Mercer — new story engine", config: branchingSuffrage, color: "bg-sky-900 hover:bg-sky-800", subColor: "text-sky-300" },
  ];

  const visibleCampaigns = isTeacherMode 
    ? campaigns 
    : campaigns.filter(c => (c.config as any).isPublished);

  if(campaignId==="silkroad")return <SilkRoad onBack={backToMenu}/>;
  if(campaignId==="crusades")return <Crusades onBack={backToMenu}/>;
  if(campaignId==="lewisclark")return <GeneratedCampaign onBack={backToMenu}/>;
  if(campaignId==="joseph")return <GeneratedCampaign data={josephReconstruction as unknown as CampaignData} onBack={backToMenu}/>;
  if(campaignId==="narrative-meiji")return <GeneratedCampaign data={narrativeDemo as unknown as CampaignData} onBack={backToMenu}/>;
  if(campaignId && BRANCHING_STORIES[campaignId])return <BranchingPlayer story={BRANCHING_STORIES[campaignId]} onBack={backToMenu}/>;
  if(campaignId==="generator")return <GeneratorUI onBack={backToMenu}/>;

  if(!campaignId)return(
    <div className="h-screen bg-stone-900 text-stone-100 flex flex-col items-center justify-center relative" style={{fontFamily:"'Georgia', serif"}}>
      {/* Teacher Mode Toggle */}
      <div className="absolute top-4 right-4 flex items-center gap-2">
        <span className="text-[10px] font-bold text-stone-500 uppercase tracking-widest">Teacher God Mode</span>
        <button 
          onClick={() => setIsTeacherMode(!isTeacherMode)}
          className={`w-10 h-5 rounded-full relative transition-colors ${isTeacherMode ? 'bg-amber-600' : 'bg-stone-700'}`}
        >
          <div className={`absolute top-1 w-3 h-3 bg-white rounded-full transition-all ${isTeacherMode ? 'left-6' : 'left-1'}`} />
        </button>
      </div>

      <h1 className="text-3xl font-bold text-amber-400 mb-2">CAMPAIGNS</h1>
      <p className="text-stone-400 text-sm mb-8">Choose your trail.</p>
      <div className="space-y-3 w-64">
        {visibleCampaigns.map(c => (
          <button key={c.id} onClick={()=>setCampaignId(c.id)} className={`w-full py-3 ${c.color} rounded font-bold transition-colors text-left px-4 relative`}>
            {isTeacherMode && !(c.config as any).isPublished && <span className="absolute top-1 right-2 text-[8px] bg-amber-900 text-amber-300 px-1 rounded uppercase font-bold">Draft</span>}
            {c.title}<br/><span className={`text-xs font-normal ${c.subColor}`}>{c.subtitle}</span>
          </button>
        ))}
        
        <div className="border-t border-stone-700 pt-3 mt-1">
          <button onClick={()=>setCampaignId("generator")} className="w-full py-3 bg-stone-800 border border-amber-700 hover:bg-stone-700 rounded font-bold text-amber-400 transition-colors">
            + Create a Campaign
          </button>
        </div>
      </div>
    </div>
  );

  if(state.phase==="intro")return(
    <div className="h-screen bg-stone-900 text-stone-100 flex flex-col items-center justify-center" style={{fontFamily:"'Georgia', serif"}}>
      <div className="max-w-md text-center space-y-4 p-4">
        <h1 className="text-3xl font-bold text-amber-400">{ChisholmCampaign.title}</h1>
        <p className="text-stone-300">{ChisholmCampaign.subtitle}</p>
        <p className="text-stone-400 text-sm">{ChisholmCampaign.introBody}</p>
        <button onClick={start} className="px-8 py-3 bg-amber-700 hover:bg-amber-600 rounded font-bold transition-colors">BEGIN OUTFIT</button>
        <button onClick={backToMenu} className="block w-full text-stone-500 hover:text-stone-300 text-xs mt-2">← Back to Campaigns</button>
      </div>
    </div>
  );

  if(state.phase==="outfit")return<OutfitScreen onDone={onOutfitDone}/>;

  if(state.phase==="end"){
    // ── Gate: the TEKS final exam must be passed before results show ──
    if(!examPassed){
      return(
        <div className="h-screen bg-stone-900 text-stone-100 p-4 overflow-y-auto flex items-center" style={{fontFamily:"'Georgia', serif"}}>
          <div className="max-w-lg mx-auto w-full space-y-4">
            <h1 className="text-2xl font-bold text-center text-amber-400">CHECK FOR UNDERSTANDING</h1>
            <FinalExam
              questions={CHISHOLM_FINAL_EXAM}
              decisionLog={state.decisions}
              subtitle="Answer the final exam to complete the drive. Review your trail if you get stuck."
              onPass={(correct)=>{setExamScore(correct);setExamPassed(true);}}
            />
            <button onClick={backToMenu} className="block w-full text-stone-500 hover:text-stone-300 text-xs">← Back to Campaigns</button>
          </div>
        </div>
      );
    }

    const herdPct = state.outfit.herd > 0 ? r.herd / state.outfit.herd : 0;
    const revenue = state.survived ? r.herd * ChisholmCampaign.revenuePerUnit : 0;
    const cost = state.outfit.budgetSpent;
    const profit = revenue - cost;
    // Exam performance is the dominant knowledge signal in the grade:
    // a perfect 10/10 contributes the full knowledge band.
    const examKnowledge = state.historicalKnowledge + examScore * 3;
    const grade = getTrailGrade(state.survived, herdPct, examKnowledge);

    return(
    <div className="h-screen bg-stone-900 text-stone-100 p-4 overflow-y-auto" style={{fontFamily:"'Georgia', serif"}}>
      <div className="max-w-lg mx-auto space-y-4">
        <h1 className={`text-2xl font-bold text-center ${state.survived?"text-amber-400":"text-red-500"}`}>
          {state.survived ? (state.earlySale ? "SOLD ON THE TRAIL" : "ABILENE") : "TRAIL'S END"}
        </h1>
        <p className="text-center text-stone-300 text-sm">
          {state.survived
            ? state.earlySale ? `Sold the herd early. ${Math.round(progress)}% of the trail complete.`
            : `${r.herd.toLocaleString()} head delivered to the Abilene railhead. The Kansas Pacific is loading them now.`
            : `Your drive failed on day ${state.day}. The prairie keeps what it takes.`}
        </p>

        <div className="bg-stone-800 border border-stone-700 rounded p-3 space-y-1 text-xs">
          <h2 className="text-amber-300 font-bold uppercase tracking-wide text-center mb-1">Financial Ledger</h2>
          <div className="flex justify-between text-stone-400"><span>Outfit Cost</span><span className="text-red-400">-${cost.toLocaleString()}</span></div>
          <div className="flex justify-between text-stone-400"><span>Herd Started</span><span className="text-stone-200">{state.outfit.herd.toLocaleString()} head</span></div>
          <div className="flex justify-between text-stone-400"><span>Herd Delivered</span><span className="text-stone-200">{r.herd.toLocaleString()} head ({Math.round(herdPct*100)}%)</span></div>
          {state.survived && <div className="flex justify-between text-stone-400"><span>Revenue (${ChisholmCampaign.revenuePerUnit}/head)</span><span className="text-emerald-400">+${revenue.toLocaleString()}</span></div>}
          <div className="border-t border-stone-600 mt-1 pt-1 flex justify-between font-bold">
            <span className="text-stone-200">Net Profit</span>
            <span className={profit>=0?"text-emerald-400":"text-red-500"}>{profit>=0?"+":""}${profit.toLocaleString()}</span>
          </div>
        </div>

        <div className="bg-stone-800 border border-stone-700 rounded p-3 space-y-1 text-xs">
          <h2 className="text-amber-300 font-bold uppercase tracking-wide text-center mb-1">Historical Knowledge (TEKS)</h2>
          <div className="flex justify-between font-bold">
            <span className="text-stone-200">Final Exam</span>
            <span className="text-amber-400">{examScore} / {CHISHOLM_FINAL_EXAM.length} correct</span>
          </div>
          <div className="flex justify-between font-bold">
            <span className="text-stone-200">Trail Wisdom Earned</span>
            <span className="text-amber-400">{state.historicalKnowledge} points</span>
          </div>
          <div className="w-full bg-stone-700 rounded-full h-2 mt-1">
            <div className="bg-amber-500 h-2 rounded-full transition-all" style={{width:`${Math.min(state.historicalKnowledge/30*100,100)}%`}}/>
          </div>
          {state.knowledgeLog.length > 0 && (
            <div className="mt-2 space-y-0.5">
              {state.knowledgeLog.map((log, i) => (
                <p key={i} className="text-stone-500 text-xs">📜 {log}</p>
              ))}
            </div>
          )}
          {state.historicalKnowledge === 0 && <p className="text-stone-600 text-center italic mt-1">No historical knowledge gained. You drove cattle but learned nothing about the trail's history.</p>}
        </div>

        <div className="grid grid-cols-2 gap-3 text-sm">
          <div className="bg-stone-800 border border-stone-700 rounded p-3 space-y-1">
            <h2 className="text-amber-300 font-bold text-xs uppercase tracking-wide text-center">Trail Stats</h2>
            {([["Days", `${state.day}`], ["Distance", `${Math.round(state.distance)} mi`], ["Crew Left", `${r.crew}`], ["Horses Left", `${r.horses}`]] as [string,string][]).map(([l,v])=>(
              <div key={l} className="flex justify-between text-stone-400 text-xs"><span>{l}</span><span className="text-stone-200">{v}</span></div>
            ))}
          </div>
          <div className="bg-stone-800 border border-stone-700 rounded p-3 space-y-1">
            <h2 className="text-blue-300 font-bold text-xs uppercase tracking-wide text-center">Historical Context</h2>
            {([["Trail distance", "~800 miles"], ["Typical drive", "2-3 months"], ["Herd size", "1,500-3,000"], ["Price in TX", "$4/head"]] as [string,string][]).map(([l,v])=>(
              <div key={l} className="flex justify-between text-stone-400 text-xs"><span>{l}</span><span className="text-stone-200">{v}</span></div>
            ))}
          </div>
        </div>

        <div className="text-center"><span className="text-stone-500 text-xs">TRAIL RATING: </span><span className={`text-4xl font-bold ${GC[grade]}`}>{grade}</span></div>

        <div className="bg-stone-800 border border-stone-700 rounded p-3">
          <p className="text-xs text-stone-500 leading-relaxed">{ChisholmCampaign.historicalContext}</p>
        </div>

        {state.decisions.length > 0 && (
          <button
            onClick={()=>setShowLog(true)}
            className="w-full bg-stone-800 hover:bg-stone-700 border border-stone-700 rounded p-3 text-left transition-colors"
          >
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wide">Open Campaign Log</h3>
            <p className="text-xs text-stone-400 mt-0.5">Click back through every decision, event, and answer from your drive.</p>
          </button>
        )}

        <div className="text-center pb-4 space-y-2">
          <button onClick={()=>{setState(makeInit());setUsedEvents(new Set());setExamPassed(false);setExamScore(0);}} className="px-5 py-2 bg-amber-700 hover:bg-amber-600 text-white font-bold rounded transition-colors">Run It Again</button>
          <br/><button onClick={backToMenu} className="text-xs text-stone-500 hover:text-stone-300 transition-colors">← Back to Campaigns</button>
        </div>
      </div>
      {showLog && <CampaignLogModal entries={state.decisions} onClose={()=>setShowLog(false)} />}
    </div>
    );
  }

  return(
    <div className={`west-app h-screen bg-stone-900 text-stone-100 flex overflow-hidden ${shakeClass}`} style={{fontFamily:"'Georgia', serif"}}>
      <StreakFlash streak={state.triviaStreak} />
      <div className="fixed top-1/2 left-1/2 -translate-x-1/2 pointer-events-none z-50">
        <FloatingNumbers floats={floats} />
      </div>

      {/* ── Map Sidebar ──────────────────────────────────── */}
      <div className="hidden md:flex w-[360px] lg:w-[430px] xl:w-[520px] 2xl:w-[580px] flex-shrink-0">
        <TrailMap progress={progress} day={state.day} totalDays={TOTAL_DAYS} trailPath={TRAIL_PATH} trailStops={STOPS} mapImage={MAP_IMAGE} totalDistance={TOTAL_DISTANCE} />
      </div>


      <aside className="hidden xl:flex w-72 2xl:w-80 flex-shrink-0 border-l border-stone-700 bg-stone-900/80 flex-col">
        <div className="px-3 py-2 border-b border-stone-700">
          <p className="text-xs font-bold uppercase tracking-wide text-amber-300">On the Trail</p>
          <p className="text-[11px] text-stone-400">Recent notes from camp, herd, and wagon.</p>
        </div>
        <div className="flex-1 overflow-y-auto px-3 py-2 space-y-2">
          {[...state.trailFeed].slice(-12).reverse().map((entry, idx) => (
            <div key={`${idx}-${entry.slice(0,18)}`} className={`rounded border p-2 ${idx===0 ? "border-amber-700 bg-amber-950/20" : "border-stone-700 bg-stone-800/60"}`}>
              <p className="text-[11px] leading-relaxed text-stone-300">{entry}</p>
            </div>
          ))}
        </div>
      </aside>

      {/* ── Main Game Column ─────────────────────────────── */}
      <div className="flex-1 flex flex-col overflow-hidden min-w-0 xl:px-4 2xl:px-8">
      <div className="flex-shrink-0 bg-stone-800">
        <div className="max-w-xl xl:max-w-2xl mx-auto">
          <PrairieScene progress={progress} pace={state.pace} turn={state.turn}/>
        </div>
      </div>
      <div className="flex-shrink-0 bg-stone-800 border-b border-stone-700 px-3 py-2">
        <div className="max-w-4xl mx-auto">
          <div className="grid grid-cols-6 gap-2 text-xs mb-2">
            <StatBox icon="🐂" label="Herd" value={r.herd} pulseState={pulses.herd || ""} />
            <StatBox icon="🤠" label="Crew" value={r.crew} pulseState={pulses.crew || ""} />
            <StatBox icon="🐴" label="Horses" value={r.horses} pulseState={pulses.horses || ""} />
            <StatBox icon="🔫" label="Ammo" value={r.ammo||0} pulseState={pulses.ammo || ""} />
            <StatBox icon="🛞" label="Wagon" value={r.wagonCondition||0} pulseState={pulses.wagonCondition || ""} />
            <StatBox icon="💵" label="Cash" value={r.cash||0} pulseState={pulses.cash || ""} />
          </div>
          <div className="mb-2 bg-stone-700 rounded p-1.5 text-xs text-center">
            <span className="text-stone-300">✨ Insight:</span> <span className="text-amber-400 font-bold">{state.insight}</span>
          </div>
          <div className="space-y-1">
            <ResourceBar label="🌾 Supplies" value={r.supplies} color={r.supplies<20?"bg-red-500":"bg-green-500"} pulseState={pulses.supplies || ""} />
            <ResourceBar label="😊 Morale" value={r.morale} color={r.morale<25?"bg-red-500":"bg-yellow-500"} pulseState={pulses.morale || ""} />
            <ResourceBar label="💪 Herd Cond." value={r.herdCondition} color={r.herdCondition<25?"bg-red-500":"bg-emerald-500"} pulseState={pulses.herdCondition || ""} />
          </div>
          <div className="flex items-center gap-2">
            <span className="w-20 text-stone-400 text-xs">📜 Knowledge</span>
            <div className="flex-1 bg-stone-700 rounded-full h-2"><div className="bg-amber-500 h-2 rounded-full transition-all" style={{width:`${Math.min(state.historicalKnowledge/30*100,100)}%`}}/></div>
            <span className="text-stone-500 text-xs w-6 text-right">{state.historicalKnowledge}</span>
          </div>
          <div className="flex justify-between items-center text-stone-500 text-xs mt-1">
            <span>Day {state.day}/{TOTAL_DAYS}</span>
            <button
              onClick={()=>setShowLog(true)}
              className="px-2 py-0.5 rounded border border-stone-600 text-amber-400 hover:bg-stone-700 font-bold transition-colors"
            >
              📖 Campaign Log
            </button>
            <span>{Math.round(state.distance)}/{TOTAL_DISTANCE} mi</span>
          </div>
          {state.objectiveNotice && (
            <p className="text-xs text-emerald-300 mt-1">{state.objectiveNotice}</p>
          )}
          {warningFlags.length > 0 && (
            <div className="mt-1 space-y-0.5">
              {warningFlags.map((w) => (
                <p key={w} className="text-[11px] text-amber-300">{w}</p>
              ))}
            </div>
          )}
        </div>
      </div>
      <DoomHUD members={partyMembers}/>
      <PortraitDebugPanel />
      <div className="flex-1 overflow-y-auto px-3 pb-3">
        <div className="max-w-4xl mx-auto space-y-3 mt-2">
          {state.phase==="sailing"&&(
            <div className="space-y-3">
              <div className="border border-indigo-700 rounded p-2 bg-indigo-950/40">
                <p className="text-xs text-indigo-300 font-bold">Route: {currentRouteNode.title} ({state.routeTag})</p>
                <p className="text-xs text-stone-300">{currentRouteNode.description}</p>
                {atRouteFork && (
                  <div className="mt-2 grid grid-cols-1 gap-1">
                    <p className="text-[11px] text-indigo-200 font-bold">Choose your path — the herd moves out once you decide:</p>
                    {currentRouteNode.edges.map((edge) => (
                      <button key={edge.to} onClick={() => { chooseRoute(edge.to, edge.tag); setLeftTownId(null); advanceTurn(); }} className="text-left text-xs px-2 py-1 rounded bg-indigo-900 hover:bg-indigo-800">
                        {edge.label} <span className="text-indigo-300">[{edge.tag}]</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {state.objectives.length > 0 && (
                <div className="space-y-2">
                  {state.objectives.map((obj) => (
                    <div key={obj.id} className="border border-emerald-800 rounded p-2 bg-emerald-950/30">
                      <p className="text-xs font-bold text-emerald-300">Quest: {obj.title}</p>
                      <p className="text-xs text-stone-300">{obj.description}</p>
                      <p className="text-[11px] text-stone-400">Progress: {obj.progress}/{obj.target} · {obj.expiresInTurns} turns left</p>
                    </div>
                  ))}
                </div>
              )}

              <div className="border border-stone-700 rounded p-3 bg-stone-800/80">
                <p className="text-stone-300 text-sm">{getPhrase(progress/100)}</p>
                <p className="text-stone-500 text-xs mt-1 italic">{getRegionFlavor(progress)}</p>
                {!awaitingDecision && (
                  <p className="text-amber-400/90 text-xs mt-2 font-bold trail-traveling">🐂 The drive presses north…</p>
                )}
              </div>

              {atTownStop && supplyTown.town && (
                <div className="space-y-2">
                  <div className="grid grid-cols-2 gap-2">
                    <button onClick={handleHunt} disabled={(r.ammo||0)<5} className="py-1.5 bg-amber-900 hover:bg-amber-800 disabled:opacity-40 disabled:cursor-not-allowed rounded text-xs font-bold transition-colors">
                      🔫 Hunt big game{(r.ammo||0)>=5 ? ` (${r.ammo} rounds)` : " (no ammo)"}
                    </button>
                    <button onClick={handleTrap} className="py-1.5 bg-emerald-900 hover:bg-emerald-800 rounded text-xs font-bold transition-colors">
                      🪤 Set traps (no ammo)
                    </button>
                  </div>
                  <TradePost
                    townName={supplyTown.town}
                    resources={r as Record<string, number>}
                    labels={TRADE_LABELS}
                    showKeys={["cash","supplies","horses","spareParts","herd"]}
                    moneyKey="cash"
                    offers={[
                      { id:"resupply", label:"Resupply provisions", give:{cash:95}, get:{supplies:20}, disabled:(r.cash||0)<95 },
                      { id:"repair", label:"Repair the wagon", give:{cash:140}, get:{wagonCondition:28, spareParts:1}, disabled:(r.cash||0)<140 },
                      { id:"hire", label:"Hire a trail hand", give:{cash:110}, get:{crew:1, morale:4}, disabled:(r.cash||0)<110 },
                      { id:"sell_horses", label:"Sell spare horses for cash", give:{horses:5}, get:{cash:120}, disabled:(r.horses||0)<35 },
                      { id:"horses_food", label:"Trade spare horses for food", give:{horses:5}, get:{supplies:14}, disabled:(r.horses||0)<35 },
                      { id:"sell_parts", label:"Sell a spare-parts crate", give:{spareParts:1}, get:{cash:45}, disabled:(r.spareParts||0)<2 },
                      { id:"sell_cattle", label:"Sell off cattle for cash", give:{herd:50}, get:{cash:200}, disabled:(r.herd||0)<400 },
                    ]}
                    onTrade={(o)=>handleTrade(o, supplyTown.town!)}
                    onLeave={()=>{setLeftTownId(supplyTown.town);advanceTurn();}}
                  />
                </div>
              )}

              {wagonLost && (
                <div className="border border-red-800 rounded p-2 bg-red-950/30 space-y-2">
                  <p className="text-xs text-red-300 font-bold">The chuck wagon is gone.</p>
                  <p className="text-[11px] text-stone-400">Press on by horseback and bleed supplies, or cut your losses and turn back.</p>
                  <button onClick={()=>advanceTurn()} className="w-full py-2 bg-red-900 hover:bg-red-800 rounded text-sm font-bold transition-colors">
                    Push on without the wagon →
                  </button>
                  <button onClick={()=>setState(prev=>({...prev, phase:"end", gameOver:true, survived:false, resultText:"You turned back after losing the chuck wagon."}))} className="w-full py-2 bg-stone-700 hover:bg-stone-600 rounded text-xs font-bold transition-colors">
                    ↩ Turn Back Before More Losses
                  </button>
                </div>
              )}
            </div>
          )}
          {state.phase==="sage"&&state.currentSage&&(
            <SageEncounter
              sage={state.currentSage}
              onComplete={handleSageComplete}
            />
          )}
          {state.phase==="event"&&state.currentEvent&&(
            state.currentEvent.type==="push_luck"?(
              <PushYourLuckEngine event={state.currentEvent} onUpdate={handlePushUpdate} onLeave={handlePushLeave}/>
            ):(
              <VisualNovelEngine
                currentEvent={state.currentEvent}
                handleChoice={handleChoice}
                bossHealth={r.morale}
                scoutHealth={r.morale}
                insight={state.insight}
                onSpendInsightForHints={spendInsightForHints}
                showRiskHints={state.riskHintsOn || state.historicalKnowledge >= FORESIGHT_KNOWLEDGE}
                riskHints={riskHints}
              />
            )
          )}
          {state.phase==="event_trivia"&&state.pendingEventQuestion&&(
            <div className="border border-indigo-700 rounded p-3 bg-indigo-950/40 space-y-2">
              <p className="text-sm text-indigo-200 font-bold">Quick Sage Question</p>
              <p className="text-sm text-stone-200">{state.pendingEventQuestion.question}</p>
              <div className="space-y-1">
                {state.pendingEventQuestion.choices.map((c, i) => (
                  <button key={i} onClick={() => handleEventTriviaAnswer(i)} className="w-full text-left text-xs bg-indigo-900 hover:bg-indigo-800 rounded px-2 py-1">
                    {c}
                  </button>
                ))}
              </div>
              <p className="text-[11px] text-indigo-300">Correct answer: +1 Insight. Wrong answer: no penalty.</p>
            </div>
          )}
          {state.phase==="trivia"&&state.currentTrivia&&(
            <ChisholmTriviaEngine
              question={state.currentTrivia}
              progress={progress}
              streak={state.triviaStreak}
              onComplete={handleTriviaComplete}
            />
          )}
          {state.phase==="result"&&(
            <div className="space-y-3">
              <div className="border border-stone-700 rounded p-3 bg-stone-800/80">
                <p className="text-stone-300 text-sm leading-relaxed">{state.resultText}</p>
              </div>
              <button onClick={continueGame} className="w-full py-2 bg-amber-800 hover:bg-amber-700 rounded text-sm font-bold transition-colors">Continue Trail</button>
            </div>
          )}
        </div>
      </div>
      </div>{/* end main game column */}
      {showLog && <CampaignLogModal entries={state.decisions} onClose={()=>setShowLog(false)} />}
    </div>
  );
}
