// ═══════════════════════════════════════════════════════════════
// ASSET CONFIG — maps game state to actual sprite assets
// Face PNGs generated by Grok, sliced from 2x2 character sheets
// ═══════════════════════════════════════════════════════════════

export function getDoomFace(roleId: string, health: number): string {
  const state = health > 70 ? "healthy" : health > 40 ? "tired" : health > 20 ? "hurt" : "critical";
  return `/faces/${roleId}_${state}.png`;
}

// Event backgrounds — procedural SVG until real art exists
const EVENT_BG_COLORS: Record<string, { sky: string; ground: string; accent: string }> = {
  river_crossing_early: { sky: "#c4604a", ground: "#5a6640", accent: "#4a88aa" },
  river_red:            { sky: "#cc5533", ground: "#6b5e2a", accent: "#884444" },
  stampede_night:       { sky: "#1a1a3e", ground: "#2a2a1e", accent: "#ffcc44" },
  tornado:              { sky: "#4a6a30", ground: "#5a5a30", accent: "#8aaa44" },
  prairie_fire:         { sky: "#cc5533", ground: "#4a3020", accent: "#ff6622" },
  water_scarce:         { sky: "#e8a060", ground: "#c4a060", accent: "#ffcc44" },
  good_grass:           { sky: "#3a6a9e", ground: "#4a7030", accent: "#7ab4d4" },
  default:              { sky: "#4a2a5c", ground: "#6b5e2a", accent: "#e8a060" },
};

export function getBackgroundForEvent(eventId: string): string {
  const colors = EVENT_BG_COLORS[eventId] || EVENT_BG_COLORS.default;
  const w = 480;
  const h = 320;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
    <defs>
      <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stop-color="${colors.sky}"/>
        <stop offset="100%" stop-color="${colors.accent}"/>
      </linearGradient>
    </defs>
    <rect width="${w}" height="${h}" fill="url(#sky)"/>
    <rect y="${h * 0.6}" width="${w}" height="${h * 0.4}" fill="${colors.ground}"/>
    <path d="M0,${h * 0.55} Q${w * 0.2},${h * 0.45} ${w * 0.4},${h * 0.55} Q${w * 0.6},${h * 0.48} ${w * 0.8},${h * 0.52} L${w},${h * 0.58} L${w},${h * 0.6} L0,${h * 0.6} Z" fill="${colors.ground}" opacity="0.7"/>
  </svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}
